### 1. 토큰 재발급 테스트
POST http://localhost:8080/api/auth/refresh
Refresh-Token:

### 2. 로그아웃 테스트
POST http://localhost:8080/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NzYxMjcyMjMsImV4cCI6MTc3NjE3MDQyM30.tmcw9K3ao1G41MXSpbBzQ0XgIVLLg-DJkgVAt1X2jo0

// eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlVTRVIiLCJuYW1lIjoi7LWc7ISx7JqwIiwiZW1haWwiOiJncmVlbnRqZGRuQGdtYWlsLmNvbSIsInByb2ZpbGVJbWFnZVVybCI6IiIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3Nzg5MjM2MDQsImV4cCI6MTc3ODk2NjgwNH0.GKHPR5yzBZxt87YBtaiVI40E01oe4S0jBLXqHUU5njg

### 3-1. 회원 정보 수정 테스트 (닉네임만)
PATCH http://localhost:8080/api/auth/update
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlVTRVIiLCJuYW1lIjoi7LWc7ISx7JqwIiwiZW1haWwiOiJncmVlbnRqZGRuQGdtYWlsLmNvbSIsInByb2ZpbGVJbWFnZVVybCI6IiIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3Nzg5MjQxMzYsImV4cCI6MTc3ODk2NzMzNn0.MxjynJvs733q8tyRj8Nr-GNyrhLVC2T9Yezpgpb_40Y
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "nickname": "최성흐에"
}
--WebAppBoundary--

### 3-2. 회원 정보 수정 테스트 (닉네임 + 프로필 이미지)
PATCH http://localhost:8080/api/auth/update
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlVTRVIiLCJuYW1lIjoi7LWc7ISx7JqwIiwiZW1haWwiOiJncmVlbnRqZGRuQGdtYWlsLmNvbSIsInByb2ZpbGVJbWFnZVVybCI6IiIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3Nzg5MjQxMzYsImV4cCI6MTc3ODk2NzMzNn0.MxjynJvs733q8tyRj8Nr-GNyrhLVC2T9Yezpgpb_40Y
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "nickname": "최성흐에"
}
--WebAppBoundary
Content-Disposition: form-data; name="profileImage"; filename="test-image.png"
Content-Type: image/png

< ./test-image.png
--WebAppBoundary--
### 4. 회원 탈퇴 테스트
DELETE http://localhost:8080/api/auth/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NzYxMjcyMjMsImV4cCI6MTc3ODcxOTIyM30.8tPmnNVOaQgdLESBT2lzKH2o_DOuqJ7cKm8qh4qPDfg