### 0-1. OAuth2 Google 로그인
# 브라우저에서 아래 URL 접속 후 Google 계정으로 로그인
# 로그인 후 백엔드에서 리다이렉트되고 토큰이 쿠키에 저장됨
GET http://localhost:8080/oauth2/authorization/google

### 0-2. OAuth2 Kakao 로그인
# 브라우저에서 아래 URL 접속 후 Kakao 계정으로 로그인
# 로그인 후 백엔드에서 리다이렉트되고 토큰이 쿠키에 저장됨
GET http://localhost:8080/oauth2/authorization/kakao

### 1. 토큰 재발급 테스트
POST http://localhost:8080/api/auth/refresh
Cookie: refreshToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2Iiwicm9sZSI6IlVTRVIiLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTc3OTM0NTE4MywiZXhwIjoxNzgxOTM3MTgzfQ.UyKlIf-yJ2MS0Ci2XdHwboz9DQ0DyVVcHJVESBL20LU

// eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1Iiwicm9sZSI6IlVTRVIiLCJuYW1lIjoi7LWc7ISx7J6JIiwiZW1haWwiOiJncmVlbnRqZGRuQGdtYWlsLmNvbSIsInByb2ZpbGVJbWFnZVVybCI6Imh0dHBzOi8vcHViLWM0MWE5OTE5YWJkNjQ4NjRiOTQwYzE4MWMwMzQ2MzdlLnIyLmRldi91c2Vycy81L3Byb2ZpbGUvcHJvZmlsZV8zZTU2Y2MzMi00ZTk2LTQxY2YtYjdhNC01ZmZkNGViYmRmZDkucG5nIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTc3OTI2NzE2MiwiZXhwIjoxNzc5MzEwMzYyfQ.NJTDPlSaYLMl3HbttLLBzDf9KxX8jjSCPYyiY-wZBfg

### 2. 로그아웃 테스트
POST http://localhost:8080/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1Iiwicm9sZSI6IlVTRVIiLCJuYW1lIjoi7LWc7ISx7J6JIiwiZW1haWwiOiJncmVlbnRqZGRuQGdtYWlsLmNvbSIsInByb2ZpbGVJbWFnZVVybCI6Imh0dHBzOi8vcHViLWM0MWE5OTE5YWJkNjQ4NjRiOTQwYzE4MWMwMzQ2MzdlLnIyLmRldi91c2Vycy81L3Byb2ZpbGUvcHJvZmlsZV8zZTU2Y2MzMi00ZTk2LTQxY2YtYjdhNC01ZmZkNGViYmRmZDkucG5nIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTc3OTI2NzAxNSwiZXhwIjoxNzc5MzEwMjE1fQ.mLfejfBtPZweRUtRBvflyb_m5U4th2wrXKE9A4bmxuQ
Cookie: refreshToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1Iiwicm9sZSI6IlVTRVIiLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTc3OTI2NzE2MiwiZXhwIjoxNzgxODU5MTYyfQ.6XdzvyJDG6U__00iGOf3tSyzjVMetRf0GI_Y84NcmxA
// eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlVTRVIiLCJuYW1lIjoi7LWc7ISx7JqwIiwiZW1haWwiOiJncmVlbnRqZGRuQGdtYWlsLmNvbSIsInByb2ZpbGVJbWFnZVVybCI6IiIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3Nzg5MjM2MDQsImV4cCI6MTc3ODk2NjgwNH0.GKHPR5yzBZxt87YBtaiVI40E01oe4S0jBLXqHUU5njg

### 3-1. 회원 정보 수정 테스트 (닉네임만)
PUT http://localhost:8080/api/auth/update
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2Iiwicm9sZSI6IlVTRVIiLCJuYW1lIjoi7LWc7ISx7JqwIiwiZW1haWwiOiJncmVlbnRqZGRuQGdtYWlsLmNvbSIsInByb2ZpbGVJbWFnZVVybCI6IiIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3NzkzNDUxOTQsImV4cCI6MTc3OTM4ODM5NH0.AytlFMNJai96wIs7rYFK3gj6yXjjUsKp7gJVzeuPGOU
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "nickname": "최성후이잉"
}
--WebAppBoundary--

### 3-2. 회원 정보 수정 테스트 (닉네임 + 프로필 이미지)
PUT http://localhost:8080/api/auth/update
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2Iiwicm9sZSI6IlVTRVIiLCJuYW1lIjoi7LWc7ISx7JqwIiwiZW1haWwiOiJncmVlbnRqZGRuQGdtYWlsLmNvbSIsInByb2ZpbGVJbWFnZVVybCI6IiIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3NzkzNDUxOTQsImV4cCI6MTc3OTM4ODM5NH0.AytlFMNJai96wIs7rYFK3gj6yXjjUsKp7gJVzeuPGOU
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "nickname": "최성잉"
}
--WebAppBoundary
Content-Disposition: form-data; name="profileImage"; filename="test-image2.png"
Content-Type: image/png

< ./test-image2.png
--WebAppBoundary--
### 4. 회원 탈퇴 테스트
DELETE http://localhost:8080/api/auth/delete
//eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1Iiwicm9sZSI6IlVTRVIiLCJuYW1lIjoi7LWc7ISx7J6JIiwiZW1haWwiOiJncmVlbnRqZGRuQGdtYWlsLmNvbSIsInByb2ZpbGVJbWFnZVVybCI6Imh0dHBzOi8vcHViLWM0MWE5OTE5YWJkNjQ4NjRiOTQwYzE4MWMwMzQ2MzdlLnIyLmRldi91c2Vycy81L3Byb2ZpbGUvcHJvZmlsZV8zZTU2Y2MzMi00ZTk2LTQxY2YtYjdhNC01ZmZkNGViYmRmZDkucG5nIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTc3OTI2NzE2MiwiZXhwIjoxNzc5MzEwMzYyfQ.NJTDPlSaYLMl3HbttLLBzDf9KxX8jjSCPYyiY-wZBfg
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2Iiwicm9sZSI6IlVTRVIiLCJuYW1lIjoi7LWc7ISx7JqwIiwiZW1haWwiOiJncmVlbnRqZGRuQGdtYWlsLmNvbSIsInByb2ZpbGVJbWFnZVVybCI6IiIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3NzkzNDUxOTQsImV4cCI6MTc3OTM4ODM5NH0.AytlFMNJai96wIs7rYFK3gj6yXjjUsKp7gJVzeuPGOU
Cookie: refreshToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2Iiwicm9sZSI6IlVTRVIiLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTc3OTM0NTE5NCwiZXhwIjoxNzgxOTM3MTk0fQ.U_Hb0NuVFqXpkoAymDzFZnveS2j05_mOwf9XPDv9x8k
